#!/sbin/sh
# Test Script: Recovery Flashable Zip
# 

OUTFD=/proc/self/fd/$2;
ZIPFILE="$3";
DIR=$(dirname "$ZIPFILE");

ui_print() {
  until [ ! "$1" ]; do
    echo -e "ui_print $1\nui_print" >> $OUTFD;
    shift;
  done;
}

show_progress() { echo "progress $1 $2" >> $OUTFD; }

set_progress() { echo "set_progress $1" >> $OUTFD; }

ui_print " ";
ui_print "Test Script";
ui_print "Tito";
show_progress 1.34 2;

ui_print " ";

exit 0;

